# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Latexmk
        uses: hspaans/latexmk-action@v1.0.13

      ## Commented out. We don't want to commit compiled pdf files in git 
      # - name: Push changes
      #   uses: actions-go/push@v1
      #   with:
      #     commit-files: main.pdf
      #     commit-message: Autocompile via github actions

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: true
          release_name: HEAD
          tag_name: ${{ github.ref }}
          body: "Automatically generated from most recent commit on main."
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload pdf as prerelease
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./main.pdf
          asset_name: main.pdf
          asset_content_type: application/pdf
